# Training a neural network for Banknote Authenticity Detection with Tensorflow & Keras



In [1]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In this exercise you will work with a dataset containing information about banknotes, to determines whether a banknote is fake or not. These information was extracted from images that were taken for the evaluation of an authentication procedure for banknotes.
More details in:

https://archive.ics.uci.edu/ml/datasets/banknote+authentication

The list of features is:
- Variance of Wavelet Transformed image (continuous).
- Skewness of Wavelet Transformed image (continuous).
- Kurtosis of Wavelet Transformed image (continuous).
- Entropy of image (continuous).

The last column of the dataset indicates the target variable (label), which is represented by the class a banknote belongs to:
- Class (0 for authentic, 1 for inauthentic).

As first task define read the .csv file into a pandas dataframe called df_banknote. 
Pay attention that the original file doesnot include a header. For later convenience, while reading the file into the dataframe,
you should also assign name to the column features, namely "Variance", "Skewness", "Kurtosis", "Entropy", "Class"

In [10]:
df_banknote = pd.read_csv("data_banknote_authentication.txt", sep=",", names=["Variance", "Skewness", "Kurtosis", "Entropy", "Class"])
df_banknote

Variance  Skewness  Kurtosis  Entropy  Class
0      3.62160   8.66610   -2.8073 -0.44699      0
1      4.54590   8.16740   -2.4586 -1.46210      0
2      3.86600  -2.63830    1.9242  0.10645      0
3      3.45660   9.52280   -4.0112 -3.59440      0
4      0.32924  -4.45520    4.5718 -0.98880      0
...        ...       ...       ...      ...    ...
1367   0.40614   1.34920   -1.4501 -0.55949      1
1368  -1.38870  -4.87730    6.4774  0.34179      1
1369  -3.75030 -13.45860   17.5932 -2.77710      1
1370  -3.56370  -8.38270   12.3930 -1.28230      1
1371  -2.54190  -0.65804    2.6842  1.19520      1

[1372 rows x 5 columns]

In [11]:
X = df_banknote.drop(['Class'],axis=1).values
y = df_banknote['Class'].values

X_train_full, X_test, y_train_full, y_test = train_test_split(X,y, test_size=0.20)

Print the summary statistics of the dataset and get an idea of variable ranges and values 

In [13]:
df_banknote.describe()

Variance     Skewness     Kurtosis      Entropy        Class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000

In [14]:
X_val, X_train = X_train_full[:150], X_train_full[150:] 
y_val, y_train = y_train_full[:150], y_train_full[150:]

In [15]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_val = sc.transform(X_val)
X_test = sc.transform(X_test)

### Create and train the model


Now the main task is for you to define a Neural Network model!
You decide to use a neural network model to build a classifier, which takes as input all available features (how many there are?) and predicts the most likely class, to which a sample belongs to. 

Write the code in the next cell to build a fully connected neural network composed by 2 hidden layers, with the following structure:
-	Layer 1: 16 nodes (or neurons), each with a Tanh activation function 
-	Layer 2: 8 nodes (or neurons), each with a ReLU activation function  

Attention: By choosing the properties of the output layer, take into account the information regarding the target variable and the type of problem you are dealing with (e.g. Regression?, Binary Classification? Multi-Class Classification?).  

In [16]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='tanh', input_dim = 4), #input_shape = (4, ) would have also work, try!
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                80        
                                                                 
 dense_1 (Dense)             (None, 8)                 136       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 225 (900.00 Byte)
Trainable params: 225 (900.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


You are almost there, what you need to do now it to choose the right loss function to use, depending on the type of problem you are dealing with. 
Insert this missing information in the cell under. 

Remember what we said in the class about the option 'from_logits'!

In [19]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),optimizer="sgd", metrics=["accuracy"]) 

In [20]:
history = model.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val))

Epoch 1/10


30/30 [==============================] - 1s 9ms/step - loss: 0.5652 - accuracy: 0.7635 - val_loss: 0.5457 - val_accuracy: 0.7267
Epoch 2/10
30/30 [==============================] - 0s 3ms/step - loss: 0.5316 - accuracy: 0.8226 - val_loss: 0.5136 - val_accuracy: 0.8133
Epoch 3/10
30/30 [==============================] - 0s 3ms/step - loss: 0.4993 - accuracy: 0.8617 - val_loss: 0.4822 - val_accuracy: 0.8400
Epoch 4/10
30/30 [==============================] - 0s 4ms/step - loss: 0.4676 - accuracy: 0.8881 - val_loss: 0.4514 - val_accuracy: 0.8600
Epoch 5/10
30/30 [==============================] - 0s 3ms/step - loss: 0.4367 - accuracy: 0.8965 - val_loss: 0.4215 - val_accuracy: 0.8933
Epoch 6/10
30/30 [==============================] - 0s 4ms/step - loss: 0.4064 - accuracy: 0.9029 - val_loss: 0.3927 - val_accuracy: 0.8933
Epoch 7/10
30/30 [==============================] - 0s 3ms/step - loss: 0.3774 - accuracy: 0.9071 - val_loss: 0.3658 - val_accuracy: 0.8933
Epoch 8/10
30/30 [

It is time now to evaluate your model, of course on the test set!

In [22]:
model.evaluate(X_test, y_test)

9/9 [==============================] - 0s 1ms/step - loss: 0.3027 - accuracy: 0.9236


[0.3026740252971649, 0.9236363768577576]

Now check directly some single predictions from the test set.

In [23]:
X_new = X_test[0:5]
y_proba = model.predict(X_new)
y_proba.round(2)

1/1 [==============================] - 0s 138ms/step


array([[0.92],
       [0.92],
       [0.39],
       [0.27],
       [0.31]], dtype=float32)

In [24]:
y_pred = (y_proba > 0.5).astype("int32")


y_pred

array([[1],
       [1],
       [0],
       [0],
       [0]])

In [25]:
y_test[0:5]

array([1, 1, 0, 0, 0], dtype=int64)

In [26]:
#using last week snippet from Logistic Regression notebook, implement the code that provide
#you the confusion matrix. 